version: '3'
services:
  mosquitto:
    image: emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"
      - "18083:18083"
    restart: unless-stopped
  
  seq:
    image: datalust/seq:latest
    container_name: seq
    ports:
      - "5341:5341"
      - "15341:80"
    volumes:
      - ./data:/data
    environment:
      - ACCEPT_EULA=Y
    restart: unless-stopped

volumes:
  mosquitto_data:
